version: '3.8'

services:
  op-geth: # this is Optimism's geth client
    pull_policy: always
    build:
      context: .
      dockerfile: ./mainnet/op-geth.Dockerfile
    ports:
      - 8545:8545       # RPC
      - 8546:8546       # websocket
      - 30303:30303     # P2P TCP (currently unused)
      - 30303:30303/udp # P2P UDP (currently unused)
      - 7301:6060       # metrics
    env_file:
      - .env
      - .env.default
      - mainnet/.env.default
    volumes:
      #- ./geth-data/:/data # enable to have persistency between restarts
      - ./mainnet/genesis.json:/genesis.json
  op-node:
    pull_policy: always
    build:
      context: .
      dockerfile: ./mainnet/op-node.Dockerfile
    depends_on:
      - op-geth
    ports:
      - 7545:8545     # RPC
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
      - 7300:7300     # metrics
      - 6060:6060     # pprof
    env_file:
      - .env
      - .env.default
      - ./mainnet/.env.default
    volumes:
      - ./mainnet/rollup.json:/rollup.json
      - ./mainnet/genesis.json:/genesis.json
