version: '3.8'

services:
  ipfs:
    image: ipfs/kubo:latest
    pull_policy: always
    container_name: ipfs
    ports:
      - "5001:5001"  # IPFS API
      - "8080:8080"  # Gateway port
    volumes:
      - /data/ipfs:/data/ipfs   # enable to have persistency between restarts

  nginx:
    image: nginx:latest
    pull_policy: always
    container_name: nginx
    depends_on:
      - ipfs
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env.nginx
    entrypoint: /bin/sh -c "/generate_nginx_config.sh && nginx -g 'daemon off;'"
    volumes:
      - ./generate_nginx_config.sh:/generate_nginx_config.sh:ro

  op-geth: # this is Optimism's geth client
    pull_policy: always
    build:
      context: .
      dockerfile: ../mainnet/op-geth.Dockerfile
    ports:
      - 8545:8545       # RPC
      - 8546:8546       # websocket
      - 30303:30303     # P2P TCP (currently unused)
      - 30303:30303/udp # P2P UDP (currently unused)
      - 7301:6060       # metrics
    env_file:
      - ../.env.default
      - ../mainnet/.env
    volumes:
      #- ./geth-data/:/data # enable to have persistency between restarts
      - ../mainnet/genesis.json:/genesis.json
  op-node:
    pull_policy: always
    build:
      context: .
      dockerfile: ../mainnet/op-node.Dockerfile
    depends_on:
      - op-geth
    ports:
      - 7545:8545     # RPC
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
      - 7300:7300     # metrics
      - 6060:6060     # pprof
    env_file:
      - ../.env.default
      - ../mainnet/.env
    volumes:
      - ../mainnet/rollup.json:/rollup.json
      - ../mainnet/genesis.json:/genesis.json
